### ISSUE TITLE
quetion about environment variable MANAGEMENT_METRICS_TAGS_APPLICATION

### ISSUE THREAD

**Issue by niuguy** [blueswen/spring-boot-observability#5]
@blueswen Thanks for sharing this, really helpful.   I got a question here maybe you can help

I noticed there are couple of env variables when deploying app-a,b,c  
```
 app-a:
    build: ./app/
    environment:
      - TARGET_ONE_HOST=app-b
      - TARGET_TWO_HOST=app-c
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4317
      - OTEL_RESOURCE_ATTRIBUTES=service.name=app-a,compose_service=app-a
      - OTEL_METRICS_EXPORTER=none
      - MANAGEMENT_METRICS_TAGS_APPLICATION=app-a
    ports:
      - "8080:8080"
    logging: *default-logging

```
I guess MANAGEMENT_METRICS_TAGS_APPLICATION is for identifying application_name when we config Grafana dashboard
![image](https://github.com/blueswen/spring-boot-observability/assets/1400357/efdc57f5-3fb1-49de-a69d-013e9b45b238)

I tried to remove this item from all three apps to verify and find there is still one option  [app] in the dropdown list

Could you halp clarify what happened & what is this env for ?
